export const DOUGH_LIMITS = {
  MAX_PANETTI:         130,
  MIN_PANETTI:         1,
  MAX_PESO_TOTALE_G:   30_000,
  MIN_PESO_TOTALE_G:   100,
  MAX_PESO_PANETTO_G:  30_000,
  MIN_PESO_PANETTO_G:  80,
  MAX_FARINA_G:        16_000,
  MIN_FARINA_G:        50,
  MIN_HYDRATION:       50,
  MAX_HYDRATION:       90,
  MIN_SALT:            0,
  MAX_SALT:            4,
  MIN_GRASSO:          0,
  MAX_GRASSO:          10,
  MIN_DOSE_LBF:        0.05,
  MAX_DOSE_LBF:        3.0,
  MIN_DOSE_IDY:        0.05,
  MAX_DOSE_IDY:        2.0,
  MIN_DOSE_LM:         10,
  MAX_DOSE_LM:         40,
  MIN_PUNTATA_H:       0,
  MAX_PUNTATA_H:       24,
  MIN_TC_H:            0,
  MAX_TC_H:            120,
  MIN_STAGLIO_H:       0,
  MAX_STAGLIO_H:       4,
};
